#include "Descriptors/descriptors.c"
#include "Drivers/VGA/vga.c"
#include "Memory/mem.c"
#include "Drivers/PIC/PIC.c"
#include "Drivers/Timers/timers.c"
#include "Processing/tasking.c"
#include "Drivers/Keyboard/Keyboard.c"
#include "Shell/Shell.c"